name: Protection Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  protection-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pyyaml
        
    - name: Run Protection Checker
      run: python scripts/protection_checker.py
      
    - name: Run Compatibility Tests
      run: |
        # Create dummy test files to prevent failure if they don't exist yet
        touch tests/test_sip_compatibility.py
        touch tests/test_audio_format.py
        python -m pytest tests/test_sip_compatibility.py -v
        python -m pytest tests/test_audio_format.py -v 